services:
    mariadb:
        image: mariadb
        volumes:
            - ~/code/mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: fainews
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: example
            MYSQL_ROOT_HOST: mariadb
        ports:
            - 3306:3306
    fainews:
        image: fainews
        command: bash -c "sleep 5 && orator migrate -f --config orator_config.py"
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        links:
            - mariadb
        depends_on:
            - mariadb
